### ISSUE TITLE
git submodule update --init --recursive not working

### ISSUE THREAD

**Issue by kb3dow** [tmk/whitefox#1]
After git clone the next step to update the submodules in not working

raj@some-machine:~/play/whitefox$ git submodule update --init --recursive
fatal: reference is not a tree: eb88b10f734ba78811fd6b01d81f8a541cee7028
Unable to checkout 'eb88b10f734ba78811fd6b01d81f8a541cee7028' in submodule path 'tmk_core'

**Comment by cubiq** [comment]
this seems to be fixed and could be closed
